language: java
sudo: false
dist: trusty
script: ant jar
jdk: oraclejdk8
before_deploy:
  - zip -r jaer-dist.zip jAERViewer1.5_linux.sh jAERViewer1.5_win64.exe SplashScreen.gif dist/ jars/ lib/ biasgenSettings/ filterSettings/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: jaer-dist.zip
  skip_cleanup: true
  on:
    tags: true
